### ISSUE TITLE
[ENHANCEMENT] Property Garage Change

### ISSUE THREAD

**Issue by TheAlphaStrain** [iNCEPTION-RP/Feedback#10]
**What feature you want to improve**
Property Garages

**How could this feature be improved? Please describe your idea as much as possible**
The ability to store people's cars who have keys to the property. Or, think of it this way, if you can't put people's car back in the garage because "You don't have keys to the car" you shouldn't be able to take out someone else's car because you don't have keys to their car.

**Additional information**
As it currently sits, if a friend gives you keys to their property, you're able to store your car in their garage. That's awesome. But, your friend can also take _your_ car out of their garage and vice versa. Cool feature in a pinch if your friend needs you to bring them their car. But, as it sits, someone who doesn't have keys can't store someone's car who does have keys to the property as it gives them a "You do not have keys to this property" prompt. BUT, if you DO have keys and you tried to store your friends' car, you STILL can't because you don't have keys to their car. As it just happened to me, I was not in city, someone took out my car by accident and it was before blackout. I wasn't able to fly in so my car went to insurance. Now I'm out $14.5k.

You're probably sitting there saying "Just get your friend to pay you back." that's a clear cut response. It's an annoyance to be out money for something that wasn't your doing and it's a annoyance to have to go to insurance just to get your car which could all be avoided by said above feature enhancement.

**Comment by ixhal** [comment]
This issue has been fixed, When we launched this feature should have been in but it went under the radar, You will get keys to the vehicle now when you take out the car.
