### ISSUE TITLE
[VEHICLE] Patriot Mil Spec - Glove box bigger than the trunk space.

### ISSUE THREAD

**Issue by Daniel-R-Blake** [iNCEPTION-RP/Feedback#13]
**What vehicle**
Patriot - military spec
**What is the issue?**
Glove box size is 17 wight.
Trunk size is 12 weight.

**What can we do to solve this issue**
Increase needed for the trunk space of the vehicle. will leave that up to the dev's of the server to determin what size it should be 😀.

**Additional information**

**Comment by bloombydee** [comment]
This vehicle has been increased to 40 trunk space, thanks for the feedback!
