### ISSUE TITLE
BF, Raptor Sport Speed [ENHANCEMENT] 

### ISSUE THREAD

**Issue by troopakoopa** [iNCEPTION-RP/Feedback#14]
**What feature you want to improve**
BF, Raptor Sport top speed is capped to 60mph 

**How could this feature be improved? Please describe your idea as much as possible**

Would like to see this at least at 100mph.

**Additional information**

**Comment by driftoooo** [comment]
Hi, thank you for your feedback.
After careful consideration, the top speed of this vehicle will be increased to 100mph.

**Comment by driftoooo** [comment]
Complete - will be available shortly. 

Thank you for your feedback, this is much appreciated.
