### ISSUE TITLE
[ENHANCEMENT] - Voice Shouting 

### ISSUE THREAD

**Issue by troopakoopa** [iNCEPTION-RP/Feedback#16]
**What feature you want to improve**
Voice Shouting 

**How could this feature be improved? Please describe your idea as much as possible**

Increase the range of Shouting

**Additional information**

There are several times that i have tired to speak with voice or others when on shouting an they cannot hear what i am saying unless they make themselves vulnerable. I think by increasing the range of shouting will help improve RP an also bring down the risk of something thinking that a person is trying to ignore RP.

**Comment by bloombydee** [comment]
Change has been pushed to address this
