### ISSUE TITLE
[BALANCE] LSPD = Sirens not on when arriving on scene. 

### ISSUE THREAD

**Issue by troopakoopa** [iNCEPTION-RP/Feedback#17]
**What is the issue involving?**
Police showing up to the scene without sirens on only lights.

**In your opinion what is the way to fix this?**

I think police should show up to scene with sirens on an lights on. Once one scene the officer than should shut off their sirens an only keep lights on. 

**Additional information**

I do understand that you want to get the element of surprise but I do think that sirens an lights should be on till on scene. 

When responding to grove street for Example i been noticing police shutting sirens off way before the 24/7 an just coming down the road with lights on, not sure if they responding to a call or just cruising around.

**Comment by ScoobYDoobY2019** [comment]
If police have there lights on. U should b able to still hear a  siren in the background still.

**Comment by AthanAlonzo** [comment]
If you are referring to " scene's "  in general, I would not suggest forcing this.

This also means the lights are bright, and noticeable from quite a distance, stating that if you pay attention you will still see them before they see you.

**Comment by TheAlphaStrain** [comment]
I think under certain circumstances Troopa is right and that sirens should be required to be on when approaching some crime scenes. Take for example, Store Robbery. If you think about it, when someone reports a robbery in progress it is safe to assume that person has a deadly weapon of some sort enforcing compliance on the victim's end, so it is to be assumed an emergency. Police sirens aren't used as a "Here we come, you should run before we get there." type of way like I feel is the way you're thinking about this. In emergency situations like I just described, there's no tactical reason for standard police officers to be tactically switching off their sirens to get the jump on whoever is committing said crime. That's more of a swat thing.

Police sirens are an indication of "We know something is going down, public safety, you hear us, you know we're coming" kind of deterrent to stop what you're doing so no one gets hurt. Depending on the time of day, what you're doing, where you are, you might not actually see the lights as all. It's not a "one size fits all" scenario with lights.

**Comment by MintPoloo** [comment]
I agree in the situation of store robberies ect yes, however, when police get a call of suspicious activity then no i dont think sirens would be needed. Also the fact certain people are doing certain activities outside of purchased properties and then when they hear sirens coming they are just sitting inside of their houses? This is taking all RP from the situation as they are never going to be caught. Also in real life if the police is tipped off regarding a drug deal they would not approach with sirens on, you normally see them approach with only lights or no lights at all. However if the situation is a atm/store robbery then yes sirens should be used.

**Comment by Wyrdwolfz** [comment]
In real life drug enforcement agencies wouldn't run around the ghetto with sirens like goons anyway.  If anything they would be using undercover cops, and undercover cars, and wires, trying to collect evidence of bigger organized crime, like gangs and cartels.  Thats how it would really be.

**Comment by troopakoopa** [comment]
The difference between IRL and a game is that you can see the lights in IRL. 

During the day lights are barely visible. 

I do agree there are times you should be lights only when rolling up but with the glare of lighting an how bright it is during the day nothing can change that. I have tried several things on my end but during the day lights are just not enough.

**Comment by bloombydee** [comment]
The reason police put on lights and sirens is to alert other drivers to clear the way. Criminals make decisions to best achieve their goals, and so do the police, and they have their reasoning and training about when to use each stage.
