### ISSUE TITLE
[VEHICLE] Ignus

### ISSUE THREAD

**Issue by Wyrdwolfz** [iNCEPTION-RP/Feedback#19]
**Ignus**

** This cars top speed is extremely low for a 565,000 dollar super car.  It tops out at 120, a crown vic goes 140**

**Increase top speed.  Either make it better or cheaper, one of the other.**

**Comment by driftoooo** [comment]
Hi there, the issue has been fixed and will be available after this restart.

Thank you for your feedback, it is appreciated.

**Comment by driftoooo** [comment]
Resolved.
