### ISSUE TITLE
[VEHICLE] Shotaro (Too Slow)

### ISSUE THREAD

**Issue by MintPoloo** [iNCEPTION-RP/Feedback#20]
**What vehicle**

Shotaro

**What is the issue?**

It is the most expensive bike in the city also known as the "tron bike" it sturggles to go above 110mph when other bikes in the city go well over 200mph. Surely this should be the fastest bike in the city? 

**What can we do to solve this issue**

Have a look at the bike and maybe look at increasing its speed so the value for money is worth it

**Comment by driftoooo** [comment]
Complete, available in live.

Thank you for your feedback, it is much appreicated.
