### ISSUE TITLE
[BALANCE] LSPD when downed

### ISSUE THREAD

**Issue by troopakoopa** [iNCEPTION-RP/Feedback#21]
**What is the issue involving?**

The issue is with LSPD using stims on other officers that are downed when no EMS is on duty, I think this can be considered a power gaming move on LSPD behalf.

**In your opinion what is the way to fix this?**

I think that a down officer should be taken into Pillbox by a fellow officer to be treated.

**Additional information**

Do we want officers back on the streets asap 100% but I feel that they should get the same treatment the suspect does or anyone else, that is downed see the local Doctor an get back on duty.  but stimmed an not seen by a local.

**Comment by MintPoloo** [comment]
I don't agree with this, when a officer is second stage down and no ems are on we are required to go to pillbox for treatment, stim packs are part of our provided kid, it's the same if the crim was to go down first stage then a buddy is able to stim them or swim themselves. It is a level playing field in this sense as both parties have access to the feature

**Comment by bloombydee** [comment]
As mint said, it is currently a level playing field
