### ISSUE TITLE
[ENHANCEMENT] Bean Machine

### ISSUE THREAD

**Issue by TheAlphaStrain** [iNCEPTION-RP/Feedback#23]
**What feature you want to improve**
Bean Machine

**How could this feature be improved? Please describe your idea as much as possible**
Add a TV to Bean Machine (If possible)

**Additional information**
For one, I dunno if you've sat in there long enough by yourself, but it's so quiet you could hear fleas makin' babies. Second, I think it would be cool to get some chill music up in there while you're working if no one is stopping by rather than playing music in your own ears and maybe having to tab out to adjust it because sometimes you just can't hear people loud enough. Lastly, be funny to walk in and someone is watching a documentary and just role playing it off, so long as it's appropriate.

**Comment by ixhal** [comment]
Its hard to regulate what gets played and what does not get played, and with it being the first contact for new people it could potentially cause them to not play the server, I would also like to mention this is part of the Gabz pack and so far when I tried to edit the inside props its not worked and caused game crashes to happen when going near the building, hopefully in the future we can do something like this, I would love to do it but the 2 issues I stated are a hard pass for me

**Comment by TheAlphaStrain** [comment]
Yeah that's why I added the (If possible) part. Being as it is an MLO, editing it straight up, as you just mentioned, proves to be difficult, just wasn't 100% sure if it was possible. I'm thinking more along the lines (Now) when we get the furnishing and stuff in the city. Can just purchase the land for Bean Machine and that should override the MLO itself to being able to add stuff such as a TV. (Like buy the land on a "Government" character.)
