### ISSUE TITLE
[BUG] Issue with the bean machine job

### ISSUE THREAD

**Issue by FreddyRP** [iNCEPTION-RP/Feedback#24]
**Describe the bug**
 I was clocked in the trucking job ,came to bean machine and could clock in ,after leaving bean machine I was still clocked in both jobs.

**To Reproduce**
1. Go to 'trucking job and clock in'
2. Clock in bean machine
3. Leave bean machine
4. You stay clocked in after leaving

**Expected behavior**
I expected to not be able to clock in into bean machine or be clocked out when leaving it

**Screenshots**
 N/A

**Additional context**
N/A

**Comment by TheAlphaStrain** [comment]
That's new. I've also not been clocked out a few times but never did anything like that. Both times for me involved getting into a car :P

**Comment by ixhal** [comment]
Issue has been fixed, Thanks for the report <3
