### ISSUE TITLE
[BUG] Issue with the Arcade

### ISSUE THREAD

**Issue by FreddyRP** [iNCEPTION-RP/Feedback#27]
**Describe the bug**
You have to have more than 1500 dollars ,if you have exactly 1500 dollars you wont be able to buy the ticket
**To Reproduce**
1. Go to the arcade
2. Click on buy ticket
4. See a message saying you don't have enough money

**Expected behavior**
You should be able to buy the ticket while having 1500dollars

**Additional context**
I did try using cash aswell ,didn't work ,still had to get at least 1501 dollars

**Comment by ixhal** [comment]
Issue has been fixed and it now takes cash and bank payment, Thanks for the report <3
