### ISSUE TITLE
hakuchou drag infinitely burns out on any kind of dirt

### ISSUE THREAD

**Issue by JoshCereal** [iNCEPTION-RP/Feedback#35]
hakuchou drag

**What is the issue?**
Burns out on any kind of dirt/gravel infinitely to the point your just stuck no matter what even in reverse,

**What can we do to solve this issue**
(Fix it burning out like that)

**Additional information**

**Comment by driftoooo** [comment]
Hi Josh, 
 Thank you for submitting the feedback regarding the Hakuchou Drag and its off-road capability.
 
After carefully reviewing the vehicle's current performance off-road, we have decided not to take any further action with this issue. 
 
Our advice to you would to be reverse the vehicle down the hill / off-road section if you get fully stuck. Although you noted in your feedback that "you're just stuck no matter what even in **reverse**", we have been unable to replicate this issue. 

I'll be closing the issue at this time, if the issue persists feel free to re-open this feedback and we will investigate this issue further.

Thank you for submitting your feedback, all feedback is greatly appreciated! Have a great rest of your day 😄
