### ISSUE TITLE
[BALANCE]  jugular 

### ISSUE THREAD

**Issue by sirmedicated** [iNCEPTION-RP/Feedback#37]
**What is the issue involving?**

jugular top speed and acceleration 

**In your opinion what is the way to fix this?**

a little bit of a higher top speed i have a sultan thats 38,000 tops out 130 and my 52,000 jugular  that can only do 115

**Additional information**

**Comment by driftoooo** [comment]
Hi there sirmedicated, 
 Thank you for your feedback and I hope that today has treated you well thus far.
 
 The vehicle was equipped with default GTA Handling, I have gone through and re-worked the vehicle fully.
 
 Changes should be live soon, keep an eye on 👀-github-updates
 
 Thank you again for your feedback, it is much appreciated!
