### ISSUE TITLE
Obey 9F - Proposed Changes

### ISSUE THREAD

**Issue by TyBeRagin** [iNCEPTION-RP/Feedback#38]
**What is the issue involving?**
Obey 9f

**In your opinion what is the way to fix this?**
So during a chase with PD, I was in the 9f and it was accelerating way too quickly and was able to top out at around 210 going uphill and 240 downhill even when beat up and smoking. Now its IRL counterparts do get to 200 mph I just don't think there should be a local vehicle that gains 50-60 more mph than the fastest PD vehicle.

**Additional information**
If needed I can get video recordings for everyone to see what is going on with the obey 9f because  in my opinion its a bit overpowered to be able to pull off from PD in a car going 200+

**Comment by MintPoloo** [comment]
It's great to see crims being honest and not just thinking "oh great I'm never getting caught" I'm assuming this will be looked at however PD do have different stages of high speed pursuit vehicles. Only certain people are trained on them but I'm almost sure we do have PD cars which Is able to go them speeds just authorization and certs are needed to pull them out :) Again thanks for being honest though!!

**Comment by driftoooo** [comment]
Hi, thank you for your feedback.

The appropriate changes have been given to best correct these issues, thank you for your time submitting this feedback request, it is greatly appreciated.

These changes will be available shortly. Thanks again.
- Liam
