### ISSUE TITLE
[VEHICLE] Cinquemila - Proposed Edit

### ISSUE THREAD

**Issue by sirmedicated** [iNCEPTION-RP/Feedback#39]
**What vehicle**
Cinquemila 

**What is the issue?**
Car seems a little sluggish and a bit back end heavy 

**What can we do to solve this issue**
Bring up torque a little same with top speed i maxed it out at 150 mph flat 

**Additional information**
love you guys(:

**Comment by driftoooo** [comment]
Hi, thank you for your feedback.

The appropriate changes have been given to best correct these issues, thank you for your time submitting this feedback request, it is greatly appreciated.

I have lowered the drag coefficient as well as increased acceleration, top speed has remained roughly the same however to ensure that we're still balanced. 

- Liam
