### ISSUE TITLE
[BUG]Remove Local (AI) Police Choppers

### ISSUE THREAD

**Issue by TheAlphaStrain** [iNCEPTION-RP/Feedback#4]
**Describe the bug**
Police Choppers seem to go down, broken, for some reason on Grove street as seen in the picture below.
**To Reproduce**
1. No idea
2. Also, no idea
3. Still no idea
4. I give up

**Expected behavior**
Local police choppers just keep dropping on grove street for no reason. No one's been shooting them. Once could be a fluke, but 2 in the same spot is a coincidence.

**Screenshots**
![image](https://user-images.githubusercontent.com/100532786/155894631-332fba1f-9490-457d-9831-1672e82f4151.png)

**Comment by ixhal** [comment]
This issue should now be resolved, Thanks for reporting it buddy.
