### ISSUE TITLE
[Brand: Annis | Model: ZR350] Need Looking Into

### ISSUE THREAD

**Issue by lAmantel** [iNCEPTION-RP/Feedback#40]
**What vehicle**
Annis ZR350
**What is the issue?**
The issue I'm having with the vehicle is that it's constantly veering off to the right. So let's say I'm driving straight and I take my hands off of all the buttons the car will start turning to the right on it's own.

I have repaired the car more than enough times about 2K spent in repairs, just to see if it was a damage related issue.

**What can we do to solve this issue**
I'm not sure if there is a way to fix it, but I'm bring it up anyways in the case that it can be looked into, to see what can be done.

**Additional information**
If you need to test drive the vehicle to get an idea of what I'm talking about, I have fully purchased it and is available to test.

**Comment by driftoooo** [comment]
Hi, thank you for your feedback.

The appropriate changes have been given to best correct these issues, thank you for your time submitting this feedback request, it is greatly appreciated.

I too personally own this vehicle and have encountered the issues mentioned above, hopefully, this fix will resolve this.

These changes will be available shortly. Thanks again.
- Liam
