### ISSUE TITLE
[VEHICLE] Karin Calico GTF 

### ISSUE THREAD

**Issue by R6Cabbage** [iNCEPTION-RP/Feedback#41]
**What vehicle**
Karin Calico GTF
**What is the issue?**
Its Too Slow It Tops at 124 on a Straight and 124 on a Down Hill

**What can we do to solve this issue**
If u can Make the top end Alittle faster then 124 it will be set 

**Additional information**
N/A

**Comment by driftoooo** [comment]
Hi, thank you for your feedback.

After carefully reviewing your request, we have decided to take no further action on this at this time.
- Liam
