### ISSUE TITLE
[BALANCE] Selling takes too long.

### ISSUE THREAD

**Issue by Daniel-R-Blake** [iNCEPTION-RP/Feedback#7]
**What is the issue involving?**
Issue is involving how long it takes to sell drugs to peds in the city. personally think it takes too long to do. to only then get rejected. In which you could be rejected 7 times in a row.

With the new Tax's in place on the drug drops. it forces people to sell to the peds (Which i actually like) But selling to peds take way too long.

In a rl situation. selling would be a quick transaction.

**In your opinion what is the way to fix this?**
I think what needs to be done is the time of selling to Peds needs to be halfed. Not saying we need to get rid of it entirely. As it would make it much harder for Police to spot it. But needs to be cut in half.

**Additional information**

**Comment by troopakoopa** [comment]
I do 100% agree with you on this

**Comment by bloombydee** [comment]
The time it takes to sell to peds is 15 seconds, we can't change this without changing the sell price and acceptance rate. I can tell you there is logic in that tracks the amount of declines you have in a row and makes sure you'll never be rejected 7 times in a row.
