### ISSUE TITLE
[VEHICLE] Hellion Trunk/Boot space too small

### ISSUE THREAD

**Issue by Daniel-R-Blake** [iNCEPTION-RP/Feedback#9]
**What vehicle**
Hellion

**What is the issue?**
Hellion is a tuck based vehicle with a trunk space of 24. Which compared to a coupe. Is the same size. Such as the Dinka Sugoi has which has 24.

**What can we do to solve this issue**
With the Hellion being a truck and with the actual comperable size of the boot space compared to the Dinka Sugoi. The boot space of the Hellion needs to be increased to most/other Trucks. this being 60/55

**Additional information**

**Comment by bloombydee** [comment]
I went in to edit this and noticed that some of these capacities aren't comparable to where we want them. Vans should be at the top with 65, open bed pickup trucks at 45 and SUV types at 40, so this is what I've set them to. LMK if this is still off
